### ISSUE TITLE
When will this be getting many of the features the one for PC has?

### ISSUE THREAD

**Issue by Canta15** [Jeswang/Hearthstone-Deck-Tracker-Mac#10]
![687474703a2f2f692e696d6775722e636f6d2f45576436556e672e6a7067](https://cloud.githubusercontent.com/assets/10172289/5975566/43e93d02-a850-11e4-8e6e-532d3e8c5bf6.jpg)
For Example can you track the cards in the other players hands, probability of getting a card, etc

**Comment by Canta15** [comment]
Just an estimated completion date if there is one. Take your time :)

**Comment by Jeswang** [comment]
Show the cards other player has played is not a hard job, but I still wondering how to present it. 
I will fulfill a deck manager first this month later.

**Comment by bmichotte** [comment]
@cerminalo054 : not sure if @Jeswang still develop this app. You can use https://github.com/bmichotte/HSTracker instead of this app
