### ISSUE TITLE
The game language bar doesn't appear and it won't let me type in the player id

### ISSUE THREAD

**Issue by Canta15** [Jeswang/Hearthstone-Deck-Tracker-Mac#11]
It says that the game preference is not setup but there is no option to change the language

**Comment by dreamyguy** [comment]
+1

When I try to add a deck by clicking on "Add Deck", I'm taken to http://www.hearthstone.com.cn/cards/builder/ and have absolutely no idea how I'm supposed to navigate in that site.

Settings give me two options: 1. Site, 2. Builder ID. I choose the site and am left wondering if this app is maintained at all?

**Comment by bmichotte** [comment]
Hey guys, not sure if @Jeswang still develop this app. You can use https://github.com/bmichotte/HSTracker instead of this app

**Comment by dreamyguy** [comment]
Cheers @bmichotte, I'm going for that one instead.
