### ISSUE TITLE
Can't add a deck

### ISSUE THREAD

**Issue by anna-sunberg** [Jeswang/Hearthstone-Deck-Tracker-Mac#12]
Hi,

I try to add a deck from heartpwn. The string is e.g. druid#33:1;34:2;73:1;237:1;280:1;282:2;329:2;459:2;548:2;587:2;602:1;605:1;620:2;633:2;683:1;7730:2;7749:2;12182:1;12191:2
but I get an empty window with no cards and no error.

**Comment by Jeswang** [comment]
You need to add the id of the deck, for example 

http://www.hearthpwn.com/decks/235258-brm-cheap-heroic-chromaggus-buff-priest 
the deck's id is 235258

**Comment by anna-sunberg** [comment]
Ok, I tried that and Deck Tracker crashes every time. That's why I figured it was the wrong way.
Actually it works with the deck you linked, but it doesn't work with none of the decks I play like http://www.hearthpwn.com/decks/230375-thaddius-resurrect-control-priest
Can it be some of the new Blackrock cards?

**Comment by anna-sunberg** [comment]
Here's the error details
http://pastebin.com/N5G4EUcY

**Comment by Jeswang** [comment]
Ok. I will debug it later today. Thank you for letting me know.
yonie90 notifications@github.com于2015年4月26日 周日下午9:56写道：

**Comment by Jeswang** [comment]
Try version 0.3 -- the latest release.
It didn't crash with id 230375 here.
