### ISSUE TITLE
Mac usage issues

### ISSUE THREAD

**Issue by rcischke** [Jeswang/Hearthstone-Deck-Tracker-Mac#15]
I have tried multiple times to use your app, but can not download any of my decks from Hearthpwn.com.  The error when I try is "request failed:  not four".  Also, I have looked online and there is no documented "Builder ID" for Hearthpwn.com that I can find.  Can you please include a full "How-To" in your homepage description for this issue?  This may be either a bug or just a lack of documentation.  If you have any questions please feel free to contact me.

**Comment by Jeswang** [comment]
Your deck number is here 
![_2015-06-05_ 9_21_44](https://cloud.githubusercontent.com/assets/553783/7997724/791b62d0-0b64-11e5-9172-449ac07efe60.png)

**Comment by rcischke** [comment]
I have tried the above solution and it gives the same error code.  This code does not update the program.  Also, there is a Hearthpwn thread about other users having the same issues with the app.

**Comment by rcischke** [comment]
It appears to be the same issue as Issue #12.

**Comment by Jeswang** [comment]
Ok, can you provide me the deck number so I can debug it?

**Comment by rcischke** [comment]
All decks I have tried failed.  The one I was using as a test
was [deck]257573[/deck]  .

On Thu, Jun 4, 2015 at 8:35 PM, Jesse Wang notifications@github.com wrote:

> Ok, can you provide me the deck number so I can debug it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jeswang/Hearthstone-Deck-Tracker-Mac/issues/15#issuecomment-109120920
> .

## 

Russell Cischke
rcischke@gmail.com
(214) 207-8757

**Comment by Jeswang** [comment]
Already download the latest version?

This deck load ok here.

![image](https://cloud.githubusercontent.com/assets/553783/7997923/8133f952-0b67-11e5-9e92-99c878f430c3.png)

**Comment by rcischke** [comment]
Yes, I have the latest version.  On the app window there are only 2
options:  "Settings" and "Add Deck".  The "Add Deck" option opens up
http://www.hearthstone.com.cn/cards/builder/ in my browser.  The "Settings"
opens up a window where you can select an upload location and put in the
Builder ID.  When I put in Hearthpwn.com as the top field and enter
[deck]257573[/deck] in the lower field and click "Update" it returns the
error "Request failed:  not four".

On Thu, Jun 4, 2015 at 8:45 PM, Jesse Wang notifications@github.com wrote:

> Already download the latest version?
> 
> This deck load ok here.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/553783/7997923/8133f952-0b67-11e5-9e92-99c878f430c3.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jeswang/Hearthstone-Deck-Tracker-Mac/issues/15#issuecomment-109122359
> .

## 

Russell Cischke
rcischke@gmail.com
(214) 207-8757

**Comment by Jeswang** [comment]
Oh my fault, just enter 257573 not "[deck]257573[/deck]".

**Comment by rcischke** [comment]
​That worked.  Thank you!  I tested the overlay out while playing a game
with deck 134111 and there was no updated count of what cards had been
drawn and what cards were left.​  Is the list and card quantity meant to be
static or dynamic as you play?  I tried playing in windowed and full
screen.  I also tried starting the app before and after Hearthstone.  The
overlay is only visible in windowed mode.

**Comment by Jeswang** [comment]
@rcischke It should remove or add overlay to drawed card. 
Try the remove part, I will test it later myself.

**Comment by rcischke** [comment]
I just tested both options which are under the "Preferences" tab, "Fade
Card" and "Remove Card".  Neither updated my card list as I played.  The
drawn cards neither faded nor were they removed from the list.  Also, thank
you very much for the replies.

On Thu, Jun 4, 2015 at 9:46 PM, Jesse Wang notifications@github.com wrote:

> @rcischke https://github.com/rcischke It should remove or add overlay
> to drawed card.
> Try the remove part, I will test it later myself.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jeswang/Hearthstone-Deck-Tracker-Mac/issues/15#issuecomment-109143652
> .

## 

Russell Cischke
rcischke@gmail.com
(214) 207-8757
