### ISSUE TITLE
Can't seem to get it to work for me.

### ISSUE THREAD

**Issue by eagles90809** [Jeswang/Hearthstone-Deck-Tracker-Mac#17]
running OSX 10.10.1
Deck is made.  But no cards are removed on draw.
Thanks in advance for your help. Am excited to use it.

**Comment by Jeswang** [comment]
Did you restart the game after start the Tracker?
Can you see the content of ~/Library/Preferences/Blizzard/Hearthstone/log.config?

**Comment by Sloo84** [comment]
I seem to have the same problem. OSX 10.10.3. I did launch the game after the Tracker. I do not know what you mean by '~/Library/Preferences/Blizzard/Hearthstone/log.config?' how can I find it?

**Comment by rodrigoAbril** [comment]
Not working for me +1

I can build decks but the app is no t tracking  anything (does it need to be fullscreen to work?).

also there is no log.config In that path or its children  
only a cache and logs folder, and a options.txt file with this

clientOptionsVersion=2
connecttobnet=True
graphicsfullscreen=False
graphicsheight=1020
graphicsquality=2
graphicswidth=1813
hasseencinematic=True
lastfaileddopversion=-1
music=True
musicvolume=0.1784662
seasonEndThreshold=1
sound=True
soundvolume=0.2134876
tutoriallostprogress=0

**Comment by Jeswang** [comment]
@rodrigoAbril The config file should be created. It must be some error in my code. I will fix it later, for temporary, you can add a config file which contains 

```
[Zone]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Bob]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Power]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Asset]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Rachelle]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
```

**Comment by rodrigoAbril** [comment]
Will try, and post the results. thanks for your help :)
