### ISSUE TITLE
Game log seems changed

### ISSUE THREAD

**Issue by jinniw43805** [Jeswang/Hearthstone-Deck-Tracker-Mac#19]
hello,i clone this app and tried

Its seem not work, and i find my hearthstone path is under:

"~/Library/Preferences/Blizzard/Hearthstone/Logs"  finder

not correspond to ~/Library/Preferences/Blizzard/Hearthstone/log.config

plz check that any log path change by Blizzard , thanks alot

**Comment by Jeswang** [comment]
~/Library/Preferences/Blizzard/Hearthstone/log.config is the config file, the log file is ~/Library/Logs/Unity/Player.log

Which do you mean?

**Comment by Jeswang** [comment]
It should be ok now.
