### ISSUE TITLE
does not compile, missing files in project

### ISSUE THREAD

**Issue by ifeherva** [Jeswang/Hearthstone-Deck-Tracker-Mac#22]
the whole AGScopeBar library is missing from repo. I am interested in contributing and working on this project, however I dont see the aim with this. 

The sources of AGScopeBar from github are not ARC so copy/pasting is no solution. Did you already have an ARC solution for that?

**Comment by ifeherva** [comment]
Nevermind, I turned off ARC on the library with -fno-objc-arc, now I get schema errors.

**Comment by ifeherva** [comment]
The pod Realm is quite different to the one used in the project. Can you please tell the version you were using?

**Comment by Jeswang** [comment]
PODS:
- AFNetworking (2.5.0):
  - AFNetworking/NSURLConnection (= 2.5.0)
  - AFNetworking/NSURLSession (= 2.5.0)
  - AFNetworking/Reachability (= 2.5.0)
  - AFNetworking/Security (= 2.5.0)
  - AFNetworking/Serialization (= 2.5.0)
  - AFNetworking/UIKit (= 2.5.0)
- AFNetworking/NSURLConnection (2.5.0):
  - AFNetworking/Reachability
  - AFNetworking/Security
  - AFNetworking/Serialization
- AFNetworking/NSURLSession (2.5.0):
  - AFNetworking/Reachability
  - AFNetworking/Security
  - AFNetworking/Serialization
- AFNetworking/Reachability (2.5.0)
- AFNetworking/Security (2.5.0)
- AFNetworking/Serialization (2.5.0)
- BlocksKit (2.2.5):
  - BlocksKit/All (= 2.2.5)
- BlocksKit/All (2.2.5):
  - BlocksKit/Core
  - BlocksKit/DynamicDelegate
  - BlocksKit/MessageUI
  - BlocksKit/UIKit
- BlocksKit/Core (2.2.5)
- BlocksKit/DynamicDelegate (2.2.5)
- hpple (0.2.0)
- libextobjc (0.4.1):
  - libextobjc/EXTADT (= 0.4.1)
  - libextobjc/EXTConcreteProtocol (= 0.4.1)
  - libextobjc/EXTKeyPathCoding (= 0.4.1)
  - libextobjc/EXTNil (= 0.4.1)
  - libextobjc/EXTSafeCategory (= 0.4.1)
  - libextobjc/EXTScope (= 0.4.1)
  - libextobjc/EXTSelectorChecking (= 0.4.1)
  - libextobjc/EXTSynthesize (= 0.4.1)
  - libextobjc/NSInvocation+EXT (= 0.4.1)
  - libextobjc/NSMethodSignature+EXT (= 0.4.1)
  - libextobjc/RuntimeExtensions (= 0.4.1)
  - libextobjc/UmbrellaHeader (= 0.4.1)
- libextobjc/EXTADT (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/EXTConcreteProtocol (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/EXTKeyPathCoding (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/EXTNil (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/EXTSafeCategory (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/EXTScope (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/EXTSelectorChecking (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/EXTSynthesize (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/NSInvocation+EXT (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/NSMethodSignature+EXT (0.4.1):
  - libextobjc/RuntimeExtensions
- libextobjc/RuntimeExtensions (0.4.1)
- libextobjc/UmbrellaHeader (0.4.1)
- Masonry (0.6.1)
- MASPreferences (1.1.2)
- OTWebImage (1.0.0)
- PXListView (0.0.1)
- PXSourceList (2.0.7)
- ReactiveCocoa (2.4.2):
  - ReactiveCocoa/UI (= 2.4.2)
- ReactiveCocoa/Core (2.4.2):
  - ReactiveCocoa/no-arc
- ReactiveCocoa/no-arc (2.4.2)
- ReactiveCocoa/UI (2.4.2):
  - ReactiveCocoa/Core
- Realm (0.89.1):
  - Realm/Headers (= 0.89.1)
- Realm/Headers (0.89.1)
- RegExCategories (1.0)
- SBJson (4.0.1)
- Sparkle (1.9.0)

DEPENDENCIES:
- AFNetworking
- BlocksKit
- hpple
- libextobjc
- Masonry
- MASPreferences
- OTWebImage (from `https://github.com/OpenFibers/OTWebImage.git`)
- PXListView
- PXSourceList (~> 2.0)
- ReactiveCocoa
- Realm
- RegExCategories (~> 1.0)
- SBJson
- Sparkle

EXTERNAL SOURCES:
  OTWebImage:
    :git: https://github.com/OpenFibers/OTWebImage.git

CHECKOUT OPTIONS:
  OTWebImage:
    :commit: cdfa36f37ee4578ec4d2f277911af60a46db14f3
    :git: https://github.com/OpenFibers/OTWebImage.git

SPEC CHECKSUMS:
  AFNetworking: 96ac9bf3eda33582701cb1fcc5b896aa1e20311e
  BlocksKit: 7f422b971407001178d181a43b99014ea2591fe6
  hpple: 3b765f96fc2cd56ad1a49aef6f7be5cb2aa64b57
  libextobjc: a650fc1bf489a3d3a9bc2e621efa3e1006fc5471
  Masonry: 4972309f2f134de9dd312f4dc4a21359b50e6caa
  MASPreferences: 32d8a2c5ef1d60b63240f5676b011ff72e194cb1
  OTWebImage: 2dfb945d3b7db6f436de9fa99159284765656b04
  PXListView: 07b11b35c07629cdb17cd817da643bbbbf89c943
  PXSourceList: 8e37978a5db6c8d8d255f8913603bcea322c6445
  ReactiveCocoa: fdf629a7321cc7504936fa86243d8c616faad302
  Realm: 9b7bebb86336e17789d7ac21b22f67a69808cb56
  RegExCategories: e68befacacd5bda853c88f70ec745cb2d0cfb89c
  SBJson: 68f16f446bd6047dc3dd1ec4919a468c2cd7fedd
  Sparkle: 75bbbc5ab2d666f7f77c241afe7fd28364a8f9f7

COCOAPODS: 0.37.2

Hope this help.

**Comment by ifeherva** [comment]
Thanks for the quick replay, I will try it later tonight.

BTW, current Realm (0.94.1) is confirmed not compiling with pods :(

Why is AGScopeBar sources missing? Licencing stuff?

**Comment by ifeherva** [comment]
I think I know why the problem is failing for most users. But first of all could you please commit the missing Files directory to the repo? It contains the log.config for example that is needed. Thanks!

**Comment by Jeswang** [comment]
THe AGScopeBar is in .gitmodules

**Comment by Jeswang** [comment]
Thank you. I don't know why I lost the config file in the project.

**Comment by Jeswang** [comment]
I add all the Pods into the repository, so I think it's going to be easy to build the whole application.

**Comment by Jeswang** [comment]
I don't know how to remove git sub modules much, if you can remove all the sub modules and keep the files, that's will be ok.

**Comment by vito-royeca** [comment]
Yes Realm 0.94.1 is not compiling with Cocoapods. I have an OS X CLI project with Objective-C and here is the error: (There are actually 197 errors)

Undefined symbols for architecture x86_64:
  "realm::BpTreeBase::replace_root(std::__1::unique_ptr<realm::Array, std::__1::default_delete<realm::Array> >)", referenced from:
      realm::Column<long long, false>::replace_root_array(std::__1::unique_ptr<realm::Array, std::__1::default_delete<realm::Array> >) in libRealm.a(RLMArray.o)
      realm::BpTree<long long, false>::clear() in libRealm.a(RLMArray.o)
      realm::BpTree<long long, false>::EraseHandler::replace_root_by_leaf(realm::MemRef) in libRealm.a(RLMArray.o)
      realm::BpTree<long long, false>::EraseHandler::replace_root_by_empty_leaf() in libRealm.a(RLMArray.o)
      realm::Column<long long, false>::replace_root_array(std::__1::unique_ptr<realm::Array, std::__1::default_delete<realm::Array> >) in libRealm.a(RLMObject.o)
      realm::BpTree<long long, false>::clear() in libRealm.a(RLMObject.o)
      realm::BpTree<long long, false>::EraseHandler::replace_root_by_leaf(realm::MemRef) in libRealm.a(RLMObject.o)
      ...
  "realm::BpTreeBase::write_subtree(realm::Array const&, unsigned long, unsigned long, unsigned long, realm::BpTreeBase::SliceHandler&, realm::_impl::OutputStream&)", referenced from:
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMArray.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMObject.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMObjectBase.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMObjectSchema.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMArrayLinkView.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMResults.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMRealmUtil.o)

**Comment by Jeswang** [comment]
I already added all the files needed to build. You should not need to run pod to make the app run.
