### ISSUE TITLE
Missing TGT cards?

### ISSUE THREAD

**Issue by petems** [Jeswang/Hearthstone-Deck-Tracker-Mac#24]
I can't find the TGT cards when I try to create a new deck.

By the way, If you need a hand with anything I'd be happy to help do some PRs :+1:

**Comment by zduci** [comment]
Noticed it's missing Wyrmrest Agent

**Comment by Jeswang** [comment]
Will update TGT cards this week.

2015-09-08 2:41 GMT+08:00 Radu Busuioc notifications@github.com:

**Comment by liuxuan30** [comment]
I remember HSTracker has updated for TGT. https://github.com/bmichotte/HSTracker.

**Comment by Jeswang** [comment]
Added TGT cards.
https://github.com/Jeswang/Hearthstone-Deck-Tracker-Mac/releases/tag/v0.41

**Comment by petems** [comment]
@Jeswang Awesome, thanks! :+1:
