### ISSUE TITLE
Search is case-sensitive

### ISSUE THREAD

**Issue by s2tephen** [Jeswang/Hearthstone-Deck-Tracker-Mac#25]
In the Deck Manager, search queries are case-sensitive, e.g. "patron" doesn't match Grim Patron but "Patron" does — would be much more convenient if this were not the case.

**Comment by Jeswang** [comment]
Already support it in the v0.41. Please download the new release.

https://github.com/Jeswang/Hearthstone-Deck-Tracker-Mac/releases/tag/v0.41
