### ISSUE TITLE
Should add a general setting dialog 

### ISSUE THREAD

**Issue by Jeswang** [Jeswang/Hearthstone-Deck-Tracker-Mac#5]
Setting dialog contain:
- Language selection
- Deck management (This may became a independent window, when it becomes, user could not only importing them, but also create decks in the app)
  - set using deck
  - import new deck
  - remove deck
- Card preview source
  - select a url
  - download a bundle

For now, I just thought about those ideas.

**Comment by bmichotte** [comment]
I dont think card management should be added on setting dialog. Should be only language sélection, and some preferences such as fonts or things like this.

I will work on this one because I think it's a very important step (lot of future work depends on settings)

**Comment by Jeswang** [comment]
OK, I will make an independent deck management window.
