### ISSUE TITLE
Card's font was not good enough

### ISSUE THREAD

**Issue by Jeswang** [Jeswang/Hearthstone-Deck-Tracker-Mac#6]
For Chinese, the size is proper, but for English or other languages, it's a little bit too big.

The font should have a outside blur black(?) border, which seems can't fulfilled by [NSMutableAttributedString drawInRect]

**Comment by bmichotte** [comment]
By changing the font, it looks like this which is better imho

![capture d ecran 2015-01-18 a 15 18 06](https://cloud.githubusercontent.com/assets/235510/5792675/5d9fd7b2-9f25-11e4-9275-1c76a344a25a.png)
